name: build-top200

on:
  push:
    paths:
      - 'scripts/build_top200/**'
      - 'tests/test_build_top200/**'
      - '.github/workflows/build-top200.yml'
  pull_request:
    paths:
      - 'scripts/build_top200/**'
      - 'tests/test_build_top200/**'
      - '.github/workflows/build-top200.yml'
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/uv-installer@v1
      - run: uv run ruff check .
      - run: uv run mypy scripts/build_top200 tests/test_build_top200
      - run: uv run pytest tests/test_build_top200

  dry-run:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/uv-installer@v1
      - run: uv run python -m scripts.build_top200 --langs en,ja --dry-run --freq-dir build
      - uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: build/BUILD_REPORT.json
