name: Upload Python Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Update version in pyproject.toml
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          sed -i "s/version = \"{{version}}\"/version = \"$VERSION\"/g" pyproject.toml

      - name: Set up Python and uv
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "uv"

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install '.[dev]'

      - name: Run ruff
        run: uv run ruff check .

      - name: Run mypy
        run: uv run mypy .

      - name: Build package
        run: uv run python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
